### ISSUE TITLE
Referencing I-Ds as "Work in Progress"

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-rpc-rfc7322bis#4]
The guidance is currently incorrect per Heather's message to rfc-interest:

https://www.rfc-editor.org/pipermail/rfc-interest/2019-September/010672.html

**Comment by ajeanmahoney** [comment]
Working link: https://mailarchive.ietf.org/arch/msg/rfc-interest/e6EnGzX67D9NkoZv7JLIvam2J80/

**Comment by ajeanmahoney** [comment]
This issue was addressed in draft-flanagan-7322bis-04.
